import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const Grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Civight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Grotesk.className}>{children}</body>
    </html>
  );
}
